//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by GUIConfigTool.rc
//
#define IDI_PROGRAMICON                 1
#define IDC_BTN_FINDPREV                3
#define IDC_BTN_SELECT_FOLDER           3
#define IDCLOSE                         8
#define IDMENU_WRAPPERWIN_MAIN          101
#define ID_MENU_WRAPPERWIN_MAIN         101
#define IDACCEL_WRAPPERWIN_MAIN         102
#define ID_ACCEL_WRAPPERWIN_MAIN        102
#define IDB_BOOTSELBUTTON               103
#define IDB_DISCONNECT                  104
#define ID_HTML_CONFIGTOOLHELP          105
#define IDB_LOGO                        106
#define IDB_KEYBOARD                    107
#define IDD_PROPS_EDITOR                107
#define IDB_XBOX                        108
#define IDB_GAMEPAD_BTN_OFF             109
#define IDB_GAMEPAD_BTN_ON              110
#define IDB_SHIFTICON                   111
#define IDB_MENUICON_HELP               112
#define IDB_OUTPUT_ATTR_ICONS           113
#define ID_MENU_CONFIGEDITWIN           114
#define ID_ACCEL_CONFIGEDITWIN          115
#define ID_MENU_LOGWIN                  116
#define ID_ACCEL_LOGWIN                 117
#define IDB_EDITTOOLS                   118
#define ID_ACCEL_DEVICEWIN              118
#define IDD_SAVEDISCARD                 119
#define ID_ACCEL_BOOTLOADERWIN          119
#define IDB_ERROR                       120
#define ID_ACCEL_CONFIGEDITWIN_EMACS    120
#define IDD_MSGBOX                      121
#define ID_ACCEL_CONFIGEDITWIN_CTRLX    121
#define IDD_MSGBOX_YESNO                122
#define ID_ACCEL_CONFIGEDITWIN_ESC      122
#define IDD_MSGBOX_WITH_CHECKBOX        123
#define ID_ACCEL_NUDGEWIN               123
#define ID_MENU_OVERVIEWWIN             124
#define ID_MENU_DEVICEWIN               125
#define IDD_FLASH_COPY_PROGRESS         125
#define ID_MENU_BOOTLOADERWIN           126
#define IDD_GOTOLINENUM                 129
#define IDD_FLASH_SIZE                  131
#define ID_CTXMENU_LOGWIN               133
#define ID_CTXMENU_CONFIGEDITWIN        134
#define IDD_SETTINGS                    134
#define ID_MENU_PLUNGERWIN              135
#define IDB_NO_XBOX                     138
#define IDB_GAMEPAD_BTN_NA              139
#define IDB_BOOTDRIVEICON               140
#define IDB_NEWDEVICON                  141
#define IDB_PINSCAPEDEVICON             142
#define IDB_PINSCAPEOFFLINEICON         143
#define IDB_PICO_DIAGRAM                145
#define IDB_PICO_DIAGRAM_HILITED        147
#define IDD_EDITOR_PREFS                148
#define ID_CTXMENU_IRSCOPE              150
#define IDD_BLANK_CONFIG_OPTIONS        151
#define IDD_CONFIRM_SAVE_TO_PICO        153
#define ID_CTXMENU_OVERVIEWWIN          156
#define IDD_CONFIGEDITOR_PAGESETUP      157
#define ID_MENU_IRTESTERWIN             157
#define ID_MENU_NUDGEWIN                158
#define ID_CTXMENU_NUDGEWIN             159
#define IDB_NUDGE_CROSSHAIRS            159
#define IDD_INSTALL_WEBVIEW2            160
#define IDB_HELPTOOLS                   162
#define ID_MENU_HELPWIN                 163
#define IDB_BITMAP1                     164
#define IDB_OPENPINDEV_BUTTONS          164
#define ID_CTXMENU_DEVICEBUTTON         164
#define ID_CTXMENU_BOOTLOADERBUTTON     165
#define IDD_WORKER_UPDATE_SUCCESS       165
#define ID_CTXMENU_IRCMDHIST            166
#define IDC_TXT_SAVEQUERY               1001
#define IDC_ERROR_ICON                  1002
#define IDC_TXT_SAVEQUERY2              1002
#define IDC_TXT_ERROR                   1003
#define IDC_TXT_SAVEQUERY3              1003
#define IDC_BOTTOM_BAR                  1004
#define IDC_MESSAGE_CHECKBOX            1005
#define IDC_TXT_TRANSFER_DESC           1006
#define IDC_PROGRESS                    1007
#define IDC_TXT_TRANSFER_PCT            1008
#define IDC_TXT_BANNER                  1010
#define IDC_CK_REGEX                    1011
#define IDC_EDIT_LINENUM                1012
#define IDC_CK_PRESERVECASE             1012
#define IDC_RB_1MB                      1014
#define IDC_RB_2MB                      1015
#define IDC_BTN_FINDNEXT                1015
#define IDC_RB_4MB                      1016
#define IDC_TAB_MAIN                    1016
#define IDC_RB_8MB                      1017
#define IDC_CK_EMACSKEYS                1017
#define IDC_RB_16MB                     1018
#define IDC_CK_INDENTWITHTABS           1018
#define IDC_EDIT_TABSIZE                1019
#define IDC_RB_INDENT_WITH_TABS         1021
#define IDC_RB_INDENT_WITH_SPACES       1022
#define IDC_EDIT_TAB_SIZE               1023
#define IDC_BTN_REPLACE                 1024
#define IDC_SPIN_TAB_SIZE               1024
#define IDC_BTN_REPLACEALL              1025
#define IDC_RB_WINDOWS_KEYS             1025
#define IDC_TXT_MODLIST                 1025
#define IDC_RB_EMACS_KEYS               1026
#define IDC_RB_BLANK                    1026
#define IDC_RB_STARTER                  1027
#define IDC_RB_EXPAN                    1028
#define IDC_RB_PROEXPAN                 1028
#define IDC_RB_BLANK_SAFEMODE           1029
#define IDC_RB_DIYEXPAN                 1029
#define IDC_RB_STARTER_SAFEMODE         1030
#define IDC_CK_CONFIRM_SAVES            1031
#define IDC_CHECK1                      1032
#define IDC_CK_LINENUMBERS              1032
#define IDC_CK_STOP_ASKING              1032
#define IDC_CK_CHECK_RULES_BEFORE_SAVE  1032
#define IDC_EDIT_MARGIN_LEFT            1033
#define IDC_CK_CONFIRM_SAVES2           1033
#define IDC_CK_ENABLEAUTOCOMPLETE       1033
#define IDC_RB_WRAP                     1034
#define IDC_CK_AUTOBACKUPENABLE         1034
#define IDC_EDIT_MARGIN_RIGHT           1035
#define IDC_CK_AUTOBACKUPCLEANUPENABLE  1035
#define IDC_EDIT_MARGIN_TOP             1036
#define IDC_EDIT_MARGIN_BOTTOM          1037
#define IDC_RB_TRUNC                    1038
#define IDC_EDIT_HEADER                 1039
#define IDC_CK_WORDMATCH                1040
#define IDC_EDIT_FOOTER                 1040
#define IDC_CK_CASEMATCH                1041
#define IDC_CK_MONOCHROME               1041
#define IDC_BTN_HELP                    1042
#define IDC_EDIT_AUTO_BACKUP_FOLDER     1043
#define IDC_EDIT_AUTOBACKUPFOLDER       1043
#define IDC_EDIT_AUTOBACKUPCLEANUPDAYS  1045
#define IDC_EDIT_FINDWHAT               1152
#define IDC_EDIT_REPLACEWITH            1153
#define DLG_FINDREPLACE                 1541
#define IDD_BLANK_SAFEMODECONFIG_OPTIONS1 1542
#define IDD_BLANK_SAFEMODECONFIG_OPTIONS 1542
#define IDD_BASEWIN_PAGESETUP           1543
#define IDD_LOGVIEWER_PAGESETUP         1544
#define IDD_SAVE_TO_PICO_SCHEMA_ERRORS  1545
#define ID_HELP_HELP                    40001
#define ID_HELP_ABOUT                   40002
#define ID_FILE_EXIT                    40003
#define ID_FILE_PROGRAMPICO             40004
#define ID_FILE_SAVETOFILE              40005
#define ID_FILE_IMPORTFROMFILE          40006
#define ID_FILE_RELOADFROMPICO          40007
#define ID_EDIT_CUT                     40008
#define ID_EDIT_COPY                    40009
#define ID_EDIT_PASTE                   40010
#define ID_EDIT_DELETE                  40011
#define ID_EDIT_GOTOLINENUMBER          40012
#define ID_EDIT_FIND                    40013
#define ID_EDIT_FINDREPLACE             40014
#define ID_EDIT_UNDO                    40015
#define ID_EDIT_REDO                    40016
#define ID_EDIT_SELECTALL               40017
#define ID_EDIT_FIND50018               40018
#define ID_FILE_CHECKERRORS             40019
#define ID_EDIT_FINDNEXT                40036
#define ID_DEVICE_REBOOT                40038
#define ID_DEVICE_BOOTLOADERMODE        40039
#define ID_DEVICE_REBOOT40040           40040
#define ID_DEVICE_BOOTLOADERMODE40041   40041
#define ID_FILE_EXIT40042               40042
#define ID_DEVICE_INSTALLFIRMWARE       40044
#define ID_DEVICE_CLEARCONFIGURATION    40045
#define ID_DEVICE_FULLFACTORYRESET      40046
#define ID_DEVICE_INSTALLFIRMWARE40047  40047
#define ID_DEVICE_CLEARFLASHFILEAREA    40048
#define ID_DEVICE_CLEARENTIREFLASH      40049
#define ID_DEVICE_REBOOT40050           40050
#define ID_DEVICE_OPENINWINDOWSEXPLORER 40051
#define ID_DEVICE_OPENINEXPLORER        40052
#define ID_BACKUP_EXPORTFULLFLASHIMAGE  40053
#define ID_BACKUP_EXPORTDATAAREAIMAGE   40054
#define ID_BACKUP_RESTOREEXPORTEDIMAGE  40055
#define ID_EDIT_CLEARALL                40056
#define ID_DEVICE_SAFEMODE              40062
#define ID_CHORD_CTRLX                  40067
#define ID_CHORD_ESC                    40068
#define ID_EDIT_GOTOTOP                 40071
#define ID_EDIT_PAGEUP                  40073
#define ID_EDIT_GOTOEND                 40075
#define ID_EDIT_LINESCROLLUP            40080
#define ID_EDIT_SWAPANCHOR              40082
#define ID_EDIT_SAVETOFILE              40086
#define ID_EDIT_SETANCHOR               40089
#define ID_EDIT_PAGEDOWN                40090
#define ID_EDIT_LINESCROLLDOWN          40094
#define ID_EDIT_TRANSPOSECHAR           40095
#define ID_EDIT_CANCELMODE              40096
#define ID_EDIT_OPENLINE                40099
#define ID_EDIT_QUOTECHAR               40101
#define ID_EDIT_FINDPREV                40102
#define ID_EDIT_REVFIND                 40103
#define ID_VIEW_REFRESHWINDOW           40105
#define ID_FILE_SAVESETTINGS            40108
#define ID_FILE_RELOADSETTINGSFROMPICO  40109
#define ID_PLUNGER_SAVESETTINGSTOPICOFLASH 40110
#define ID_PLUNGER_RESTORESETTINGSFROMPICO 40111
#define ID_PLUNGER_CALIBRATE            40112
#define ID_PLUNGER_SAVESETTINGSTOPICO   40113
#define ID_LOGWINDOWCONTEXTMENU_TEXTEDITOR 40114
#define ID_TOOLS_TEXTEDITORPREFS        40115
#define ID_EDIT_EDITORPREFERENCES       40116
#define ID_IROSCILLOSCOPE_SAVERAWPULSEDATA 40117
#define ID_IROSCILLOSCOPE_CLEARSCOPEVIEW 40118
#define ID_IRSCOPE_SAVE                 40119
#define ID_IRSCOPE_CLEAR                40120
#define ID_FILE_IMPORTFROMTEMPLATEFILE  40121
#define ID_FILE_PRINT                   40123
#define ID_FILE_PRINTSETUP              40124
#define ID_FILE_PAGESETUP               40125
#define ID_FILE_PRINTPINOUTDIAGRAM      40126
#define ID_FILE_PAGESETUP40127          40127
#define ID_EDIT_COPYPINOUTDIAGRAM       40128
#define ID_FILE_PAGESETUP40129          40129
#define ID_IROSCILLOSCOPE_COPYRAWPULSEDATA 40130
#define ID_EDIT_COPYPULSES              40131
#define ID_IRSCOPE_COPY                 40132
#define ID_NUDGE_CALIBRATENOISELEVEL    40133
#define ID_NUDGE_CALIBRATE              40134
#define ID_NUDGE_SETCENTERPOINTNOW      40135
#define ID_NUDGE_CENTER                 40136
#define ID_NUDGE_SETCENTERPOINT         40137
#define ID_HELP_JSONSYNTAXGUIDE         40138
#define ID_HELP_PROPERTYREFERENCE       40139
#define ID_HELP_ABOUTTHEPINSCAPEPICOCONFIGTOOL 40140
#define ID_HELP_ABOUTTHEPINSCAPEPICOCONFIGTOOL40141 40141
#define ID_HELP_ABOUTTHEPINSCAPEPICOCONFIGTOOL40142 40142
#define ID_HELP_ABOUTTHEPINSCAPEPICOCONFIGTOOL40143 40143
#define ID_HELP_ABOUTTHEPINSCAPEPICOCONFIGTOOL40144 40144
#define ID_HELP_ABOUTTHEPINSCAPEPICOCONFIGTOOL40145 40145
#define ID_HELP_ABOUTTHEPINSCAPEPICOCONFIGTOOL40146 40146
#define ID_NAVIGATE_BACK                40147
#define ID_NAVIGATE_HOME                40148
#define ID_NAVIGATE_FORWARD             40149
#define ID_NUDGE_SAVESETTINGS           40150
#define ID_NUDGE_REVERTSETTINGS         40151
#define ID_FILE_SAVESETTINGSCALIBRATIONTOPICOFLASH 40152
#define ID_FILE_REVERTSETTINGS          40153
#define ID_DEVICEOVERVIEWCONTEXTMENU_REPAIRJOY 40154
#define ID_DEVICE_REPAIRJOYCPL          40155
#define ID_DEVICE_REPAIRJOY             40156
#define ID_DEVICE_REPAIRJOY40157        40157
#define ID_DEVICE_REPAIRJOY40158        40158
#define ID_Menu                         40159
#define ID_EDIT_CLEARCOMMANDLIST        40160
#define ID_EDIT_COPYHISTITEM            40161
#define ID_EDIT_TRANSMITHISTITEM        40162
#define ID_LOGWINDOWCONTEXTMENU_HELPONSELECTION 40163
#define ID_HELP_ON_SELECTION            40164
#define ID_DEVICEOVERVIEWCONTEXTMENU_REBOOT 40165
#define ID_DEVICE_ENTERFACTORYMODE      40166
#define ID_DEVICEOVERVIEWCONTEXTMENU_REBOOTTOFACTORYMODE 40167
#define ID_DEVICE_REBOOTTOFACTORYMODE   40168
#define ID_DEVICE_REBOOTTOFACTORYMODE40169 40169

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        167
#define _APS_NEXT_COMMAND_VALUE         40170
#define _APS_NEXT_CONTROL_VALUE         1046
#define _APS_NEXT_SYMED_VALUE           801
#endif
#endif
