ClearConfig.uf2 : CreateConfigClearerUF2.exe
    .\CreateConfigClearerUF2 $@

CreateConfigClearerUF2.exe : CreateConfigClearerUF2.cpp
    cl $**

clean:
    del ClearConfig.uf2
    del CreateConfigClearerUF2.obj
    del CreateConfigClearerUF2.exe
